# Command is 'kubectl apply -f <file.yaml>'. Config file to have all the data regarding deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80


#  ubuntu@ip-172-31-13-34:~$ vim nginx-deployment.yaml
#  ubuntu@ip-172-31-13-34:~$ kubectl apply -f nginx-deployment.yaml
#  deployment.apps/nginx-deployment created
#  ubuntu@ip-172-31-13-34:~$ kubectl get pod
#  NAME                                READY   STATUS              RESTARTS   AGE
#  nginx-deployment-644599b9c9-c7m2s   0/1     ContainerCreating   0          6s
#  ubuntu@ip-172-31-13-34:~$ kubectl get pod
#  NAME                                READY   STATUS    RESTARTS   AGE
#  nginx-deployment-644599b9c9-c7m2s   1/1     Running   0          24s
#  ubuntu@ip-172-31-13-34:~$
