# Create a new Deployment with the below attributes using your own deployment definition file.
# Name: httpd-frontend;
# Replicas: 3;
# Image: httpd:2.4-alpine
apiversion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    type: frontend
spec:
  template:
    metadata:
      name: httpd-test-deployment
      labels:
        type: frontend
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
      type: frontend
