apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-testing
  labels:
    purpose: testing-deployment
    owner: kumarrav
spec:
  template:
    metadata:
      name: nginx-k8s
      labels:
        purpose: test
        owner: kumarrav
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
  replicas: 6
  selector:
    matchLabels:
      purpose: test
