apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-app
  labels:
    purpose: testing
    owner: kumarrav

spec:
  template:
    metadata:
      name: nginx-app
      labels:
        purpose: testing
        owner: kumarrav
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
        #- name: busybox
        #  image: busybox
  replicas: 3
